server:
  port: 8080

spring:
  application:
    name: technical-test-progress-soft

  datasource:
    url: jdbc:postgresql://localhost:5432/fx_deals
    username: postgres
    password: soumia
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  logging:
    level:
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
